### ISSUE TITLE
Catch-MsGraphError : Request Authorization failed

### ISSUE THREAD

**Issue by atiedemann** [AzureAD/AzureADAssessment#10]
I start the assessment with an non privileged user. I have Global Reader and Security Reader role assignments and you wrote, that for that we need the following rights.

Azure Active Directory as Global Administrator or Global Reader

When I start the assessment with the roles described above I get this error.
`
Catch-MsGraphError : Request Authorization failed
At C:\Program Files\WindowsPowerShell\Modules\AzureADAssessment\2.0.779889\internal\Get-MsGraphResults.ps1:247 char:25
+                 catch { Catch-MsGraphError $_ }
+                         ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Write-Error], WebException
    + FullyQualifiedErrorId : accessDenied,Catch-MsGraphError
`

And when I check the outputs, the following file is missing: 
- emailOTPMethodPolicy.json

When I start the assessment with Global administrative rigths no error occurs and the missing file is created.

Have a nice day
Arne

**Comment by cblomart** [comment]
Hi Arne,

Collecting the Email OTP policy does require Global Administrator.
The error was not stopping data collection. I update the script to provide a warning rather than an error.

Cédric

**Comment by TomAafloen** [comment]
I asked Microsoft a week ago (on Yammer) about why Security **Reader** cannot **read** this setting. If it is intentional or something that might be fixed. No response yet.

Tom

**Comment by merill** [comment]
@TomAafloen it's not intentional and is a bug. A fix is on the way.

**Comment by atiedemann** [comment]
@All 
Thanks for the update
