### ISSUE TITLE
Loading blocked by failures with other queries

### ISSUE THREAD

**Issue by DeanGross** [AzureAD/AzureADAssessment#12]
When I open the AzureADAssessment-ConditionalAccess powerbi file, I get many errors like " conditionalAccessPolicy
Loading blocked by failures with other queries." Is this expected behavior if there are not any CA policies in the tenant? I am in a tenant that has the Security Defaults enabled. Would this be causing this type of error?

**Comment by jasoth** [comment]
If you look through the list of other queries, it should show an error message for the dependent query. It could be one of the files was not found in the directory specified. If you can provide the error detail and list of output files being used as input to the dashboard, we can take a closer look.

**Comment by cblomart** [comment]
Hi @samredinet, @DeanGross, we have realeased a new version that solves the some loading issues.
We also documented a workaround in the README which is to disable security check for the powerbi file as it loads data from the same location (csv and json in the same folder).

**Comment by samredinet** [comment]
@cblomart 
Hi,

Appreciate the update. When loading the PowerBi template "AzureADAssessment", i still recieve

"Expression.Error: The column 'userType' of the table wasn't found.
Details:
    userType"

The column 'userType' of the table wasn't found.

![image](https://user-images.githubusercontent.com/50487351/174767344-3927c442-4046-4533-931b-51d2a3d79d90.png)

**Comment by cblomart** [comment]
Thanks from the feedback!
Is suppose you download the latest PowerBI templates either via the ```Complete-AADAssessmentReports``` or by downloading the m from the assets folder?
