### ISSUE TITLE
Disconnecting

### ISSUE THREAD

**Issue by DeanGross** [AzureAD/AzureADAssessment#13]
I don't see a disconnect-azureAdAssessment cmdlet. What is the recommended method for running this against multiple tenants?

**Comment by jasoth** [comment]
That is a good suggestion. We can look into adding a Disconnect command for consistency.
However, in the current version you should be able to re-run the `Connect-AADAssessment -TenantId <TenantId>` command again with a different TenantId to connect to a different tenant.
