### ISSUE TITLE
Connecting to tenant as guest

### ISSUE THREAD

**Issue by DeanGross** [AzureAD/AzureADAssessment#14]
How can we connect to a tenant when we have been invited as a guest?

**Comment by jasoth** [comment]
If your guest account has been assigned the global admin role in the tenant, then you should be able to run the assessment against that foreign tenant but you will need to explicitly specify the tenant you want to connect to.
`Connect-AADAssessment -TenantId <TenantName>.onmicrosoft.com`

**Comment by DeanGross** [comment]
Thanks, but I'm confused, the parameter is called TenantId, so I would expect to enter a guid, but the example shows a domain. Is the parameter poorly named or is the sample incorrect or something else?

**Comment by jasoth** [comment]
Either value will work. A tenantId guid will work but a domain name verified in the tenant will work also and is easier to remember.
