### ISSUE TITLE
Table is malformed in Assessment Reference

### ISSUE THREAD

**Issue by TomAafloen** [AzureAD/AzureADAssessment#22]
In the Assessment Reference, the table is incorrectly formatted at the **Password Policy** Check:
https://github.com/AzureAD/AzureADAssessment/wiki/Assessment-Reference#check-password-policy
Should have 7 table rows, only the first three are correctly formatted.

**Comment by TomAafloen** [comment]
The same issue exists in the following two checks as well:

- https://github.com/AzureAD/AzureADAssessment/wiki/Assessment-Reference#check-strong-credential-management
- https://github.com/AzureAD/AzureADAssessment/wiki/Assessment-Reference#check-azure-ad-logs-archived-and-integrated-with-supportability-incident-response-plans

**Comment by TomAafloen** [comment]
And in the Notifications check, at **Notifications sent by Azure AD**:

- https://github.com/AzureAD/AzureADAssessment/wiki/Assessment-Reference#check-notifications

**Comment by cblomart** [comment]
Thanks @TomAafloen! the tables should be correctly formated now.
