### ISSUE TITLE
The property 'StatusDescription' cannot be found on this object. error in AzureADAssessment\2.2.2\internal\Get-MsGraphResults.ps1:308

### ISSUE THREAD

**Issue by sudo-vii** [AzureAD/AzureADAssessment#32]
Whenever I run  Invoke-AADAssessmentDataCollection I get the following error:

Catch-MsGraphError: C:\Users\USER\Documents\PowerShell\Modules\AzureADAssessment\2.2.2\internal\Get-MsGraphResults.ps1:308
Line |
 308 |                  catch { Catch-MsGraphError $_ }
     |                          ~~~~~~~~~~~~~~~~~~~~~
     | The property 'StatusDescription' cannot be found on this object. Verify that the property exists.

**Comment by Roahso** [comment]
me three!  Anyone going to take a look at this issue?

**Comment by cblomart** [comment]
Hi, we have promoted the preview branch.
The error handling has been updated to detect the exception type.
Can you do the assessment with the new version?

**Comment by Roahso** [comment]
Same for me:
<img width="710" alt="image" src="https://user-images.githubusercontent.com/32750783/169527852-e26ba19d-cc59-40bb-acb5-453cafca9be0.png">

**Comment by Roahso** [comment]
actually, scratch my earlier post... I forgot to update the module lolol!.  Looks like I've ran into permissions issues unrelated to this.  Thanks for the update.

**Comment by fslef** [comment]
Yep same for me. Thank you
