### ISSUE TITLE
Index was outside the bounds of the array when calling Invoke-AADAssessmentDataCollection

### ISSUE THREAD

**Issue by ztrhgf** [AzureAD/AzureADAssessment#33]
Error bellow when calling Invoke-AADAssessmentDataCollection

<img width="599" alt="image" src="https://user-images.githubusercontent.com/2930419/147565437-8abc5097-ff24-4e8c-aa91-8801a3f721de.png">

When I debug 2.2.2\internal\Expand-MsGraphRelationship.ps1 it turns out that:
- $inputObject contained one item 
<img width="549" alt="image" src="https://user-images.githubusercontent.com/2930419/147565882-c6d133aa-f595-42f5-822e-46c4a5a2d699.png"> when final block started. But $results variable was empty, because there was no user in "Exchange administrator" role! Therefore error on line [array] $refValues = $Results[$i]
- btw $uri contained directoryRoles/{0}/members/$ref

SOLUTION?
In 2.2.2\internal\Expand-MsGraphRelationship.ps1 modify both foreach 
from:
            for ($i = 0; $i -lt $InputObjects.Count; $i++) {
to:
            for ($i = 0; $i -lt $Results.Count; $i++) {

**Comment by jasoth** [comment]
The code that led to this error has been completely replaced with roleDefinitions api so this should be resolved now. Let us know if you still see any errors.
