### ISSUE TITLE
if (!(Test-MsGraphBatchError $results)) {Value cannot be null. Parameter name: source

### ISSUE THREAD

**Issue by schmarrap** [AzureAD/AzureADAssessment#48]
Have been doing some testing and trying to run through the process against my demo CDX environment and there seems to be a few issues.

1. if (!(Test-MsGraphBatchError $results)) {Value cannot be null. Parameter name: source
  I got the script to complete as there was a few null values which the script didn't expect by using try and removing remarking the following out:

$ReferencedIdCache.roleGroup.guid | Get-MsGraphResults 'groups/{0}/transitiveMembers/microsoft.graph.group?$count=true&$select=id' -Top 999 -TotalRequests $ReferencedIdCache.roleGroup.Count -DisableUniqueIdDeduplication `
            #| ForEach-Object { [void]$ReferencedIdCache.group.Add($_.id) }

3. It gave the following error but was able to generate the zip file Get-AADAssessRoleAssignmentReport -Offline -RoleAssignmentSch …| Use of the offline parameter requires that all data be provided using the data parameters.
4. Opening PowerBI I've got data issues as some files are empty as i guess is related to the export not working as expected.

I can provide access to my demo tenant for testing to confirm it's not environmental but my collogue also tried against his own CDX environment and also gave errors. When I executed against an production tenant it failed. 

I've added rough quick debugging results that might help
[AADAssessmentDebug31-05-2022.docx](https://github.com/AzureAD/AzureADAssessment/files/8801975/AADAssessmentDebug31-05-2022.docx)
.

**Comment by schmarrap** [comment]
I did a quick debug session and got some sample reports to work, did a fork and showed the changes I made . https://github.com/AzureAD/AzureADAssessment/commit/a45150f5502ede117cbc48a90df8cfc1f940aa0b

I found a few more issues to get the reporting to work.

I'll give you the details you requested a bit later today or tomorrow.

**Comment by schmarrap** [comment]
_As far as i can see "Test-MsGraphBatchError" returns correctly the error provided by Graph "Value cannot be null. Parameter name: source"_
So we can assume the error we are receiving can be ignored as you stated it's doing what you accept? I saw the script continued but only halted with the transitive member error.

**Comment by cblomart** [comment]
The goal of "Test-MsGraphBatchError" is to handle errors returned by graph so the command per se works.
What i want to look at with the correlationid and requestid is why the graph request gave an error.

**Comment by cblomart** [comment]
As per #49, guid and userType should be solved in the preview version of the module.

Concerning references to "roleAssignments.csv" vs "RoleAssignmentReport.csv" please be sure to leverage the PowerBI template bellow. It does not rely on "roleAssignements.csv":
https://github.com/AzureAD/AzureADAssessment/raw/master/assets/AzureADAssessment.pbit

**Comment by cblomart** [comment]
The update i pushed today should solve:
* Conditional Access PowerBI not handling assignments (for Break glass account exclusion)
* Automated recommendations still using roleAssignements.csv

Can you confirm it works now?

**Comment by cblomart** [comment]
@schmarrap can you give an update to those issues. We have released the new version to production (2.2.47)

**Comment by schmarrap** [comment]
Sorry was a bit stuck in a few things, will try to look at next week.

**Comment by schmarrap** [comment]
@cblomart I have tested your latest production release and it's working

**Comment by cblomart** [comment]
Thanks @schmarrap, i'll proceed an close this issue.
