### ISSUE TITLE
403 response in a few of the API Calls

### ISSUE THREAD

**Issue by LuanVCL** [AzureAD/AzureADAssessment#51]
Hello,

I'm trying to test the assessment in a test Tenant and I meet the requirements, having the Global Admin role, but i'm getting a few errors on the API calls, for example:

WARNING: GET https://graph.microsoft.com/beta/roleManagement/directory/roleAssignmentSchedules?$expand=principal(%24select%3Did)%2CroleDefinition(%24select%3Did%2CtemplateId%2CdisplayName)&$filter=status+eq+%27Provisioned%27+and+assignmentType+eq+%27Assigned%27+and+directoryScopeId+eq+%27%2F%27&$select=id%2CdirectoryScopeId%2CmemberType%2CscheduleInfo%2Cstatus%2CassignmentType; error Response status code does not indicate success: 403 (Forbidden).; attempt 5 out of 5. Retrying after 16s

Here's the debug output:

DEBUG: {
  "name": "AppExceptions",
  "time": "2022-06-10T21:15:29.8607225Z",
  "iKey": "9ef9a343-9c69-4468-a1a0-e1786a6d9f89",
  "tags": {
    "ai.application.ver": "2.2.36",
    "ai.operation.id": "ecd8a0e3-b896-4e56-92a4-9894c33227c7",
    "ai.operation.name": "Invoke-AADAssessmentDataCollection",
    "ai.operation.parentId": "",
    "ai.session.id": "236b794b-0bbd-4494-935f-9c6aad7510ff",
    "ai.user.id": "@{<Redacted>",
    "ai.device.osVersion": "Microsoft Windows 10.0.22000"
  },
  "data": {
    "baseType": "ExceptionData",
    "baseData": {
      "ver": 2,
      "properties": {
        "Culture": "en-US",
        "PsEdition": "Core",
        "PsVersion": "7.2.4",
        "DebugPreference": 2,
        "TenantId": "<Redacted>",
        "CloudEnvironment": "Global"
      },
      "exceptions": [
        {
          "hasFullStack": true,
          "parsedStack": [],
          "typeName": "Microsoft.PowerShell.Commands.WriteErrorException",
          "message": "Attempted to perform an unauthorized operation.",
          "id": 3556833
        }
      ]
    }
  }
}
DEBUG: {
  "id": "11",
  "status": 403,
  "headers": {
    "Content-Type": "application/json"
  },
  "body": {
    "error": {
      "code": "UnauthorizedAccessException",
      "message": "Attempted to perform an unauthorized operation.",
      "innerError": {
        "date": "2022-06-10T21:15:27",
        "request-id": "49bd963e-f3ea-40c2-ad4e-5185d410b1ef",
        "client-request-id": "49bd963e-f3ea-40c2-ad4e-5185d410b1ef"
      }
    }
  }
}
![image](https://user-images.githubusercontent.com/45215203/173152554-9bed7623-603a-4c90-8f6d-55b38ea10ad8.png)

**Comment by cblomart** [comment]
We have updated the preview version (2.2.44-preview) to handle those more transparently.

**Comment by cblomart** [comment]
@LuanVCL could you confirm that the newer version (2.2.47) works well for you?

**Comment by LuanVCL** [comment]
@cblomart, I tried with the latest version, but i'm still getting the same errors, I managed to "solve it" by running the assessment in my local machine instead of an Azure VM, so I suspect that the tenant is blocking connections from other regions or specific ip ranges.
I will update this issue if I manage to find the reason why it's not working on an Azure VM.

**Comment by cblomart** [comment]
So in the an azure vm on another tenant you cannot run the assessment?
I know this may look like 101 but did you confirm that the VM is using the 2.2.47 assessment version?

**Comment by LuanVCL** [comment]
I found the reason for the error, basically the VM I was using had some some configurations that were in conflict with the Tenant's Policies, so I was getting those errors only in that VM.
