### ISSUE TITLE
URI Redirect Error in USGOV

### ISSUE THREAD

**Issue by hacknorris** [AzureAD/AzureADAssessment#54]
Hello -- trying to run Connect-AADAssessment -CloudEnvironment USGOVDoD -- after authenticating I'm getting the URI Redirect mismatch error.  Normally would try modifying the uri property as noted here:  https://docs.microsoft.com/en-us/troubleshoot/azure/active-directory/error-code-aadsts50011-redirect-uri-mismatch   but i'm not seeing the ability to add this since it's found as an Enterprise App.  Would appreciate any advice or help on this.

**Comment by jasoth** [comment]
@hacknorris I added the correct redirect uri for gov tenants to our default app registration but I am not sure how long it will take to be available in gov tenants. In the meantime, you can create your own app registration within your tenant and provide the app id using the -ClientId parameter.

**Comment by jasoth** [comment]
@hacknorris I have added guidance to our readme for how to run the assessment for gov cloud tenants. We do require you to create your own app registration.
https://github.com/AzureAD/AzureADAssessment#i-have-a-tenant-in-sovereign-cloud-how-do-i-run-this-assessment
