### ISSUE TITLE
Unable to open the Power BI 'AzureADAssessment.pbit'

### ISSUE THREAD

**Issue by hitem** [AzureAD/AzureADAssessment#56]
Hello,
Im supernew to this tool and was testing it out.
I was able to follow the wiki just fine (superb one btw!), i came all the way down to opening the two Power Bi reports:
```AzureADAssessment.pbit```
```AzureADAssessment - ConditionalAccess.pbit```
The ConditionalAccess one **works just fine**, but the AzureAdAssessment **does not**. 

It has successfully created cvs and json files with content (if i open them they look correctly formated to!):
![image](https://user-images.githubusercontent.com/8977898/181216840-d2d5a035-ec21-45b4-9e4e-0b3c77ce6984.png)
(Note that i do not use any AD sync or connectors, so i skipped that step in the [pre-req](https://github.com/AzureAD/AzureADAssessment/wiki#pre-interview-checklist))

When i run the ```AzureADAssessment.pbit``` i get the following error:
![image](https://user-images.githubusercontent.com/8977898/181218379-010eb49a-8e0a-48a5-a874-99d489f7c03d.png)
Those seems to be these:
![image](https://user-images.githubusercontent.com/8977898/181218339-997eb4f3-c73d-40ef-9975-a6183fe32d3b.png)
![image](https://user-images.githubusercontent.com/8977898/181218351-216f9069-230c-4e57-bc7b-2c68a0aa4161.png)

Any help or suggestion greatly appreciated!

**Comment by myfope** [comment]
Just wanted to let everyone know: I've just run the queries to generate the pbit files and have the exact same issue - any help is much appreciated!

**Comment by merill** [comment]
Please see this FAQ question. https://github.com/AzureAD/AzureADAssessment#unable-to-load-data-in-powerbi-templates

Also remember to not close the PowerBI window when you change the setting. Instead hit refresh/reload data (or apply changes).

**Comment by myfope** [comment]
@merill thanks - I checked the FAQ but did not came across the error I saw so I did not figured out this will help. But for me the fix in the FAQ solved my issue!

**Comment by hitem** [comment]
@merill **Thank you. This did indeed resolve my issue.**
I read through the FAQ but i must have missed it completely. Much appreciated and as always, keep up the superb work!
