### ISSUE TITLE
Error on AADPremium Identifiers

### ISSUE THREAD

**Issue by bastienperez** [AzureAD/AzureADAssessment#57]
Hello,

There are an error in the AAD Premium identifiers:

File _Get-AADAssessUserReport.ps1_, the fix is:
```
$aadp1plan = "41781fb2-bc02-4b7c-bd55-b576c07bb09d"
$aadp2plan = "eec0eb4f-6444-4f95-aba0-50c24d67f998"
```

File _Invoke-AADAssessmentDataCollection.ps1_ , the fix is:
```
if ($skus | Where-Object { $_.prepaidUnits.enabled -gt 0 -and ($_.servicePlans | Where-Object { $_.servicePlanId -eq "41781fb2-bc02-4b7c-bd55-b576c07bb09d" })}) {
            $licenseType = "P1"
        } elseif ($skus | Where-Object { $_.prepaidUnits.enabled -gt 0 -and ($_.servicePlans | Where-Object { $_.servicePlanId -eq "eec0eb4f-6444-4f95-aba0-50c24d67f998" })}) {
            $licenseType = "P2"
        }
```

**Comment by jasoth** [comment]
@bastienperez I think you have the AAD premium identifiers reversed. I just looked at a P1 and a P2 user to validate and the guids in the assessment match what the API is returning for P1 and P2.

**Comment by bastienperez** [comment]
As far as I understand, my issue is valid.
I just try on tenant with P1 and the report shows me P2.

The code is: 
```
$aadp1plan = "eec0eb4f-6444-4f95-aba0-50c24d67f998
$aadp2plan = "41781fb2-bc02-4b7c-bd55-b576c07bb09d
```
But Microsoft doc  ([Licensing service plan reference](https://docs.microsoft.com/en-us/azure/active-directory/enterprise-users/licensing-service-plan-reference)) and MS graph (https://graph.microsoft.com/v1.0/subscribedSkus) give the same info:

for P1:
```
"servicePlanId": "41781fb2-bc02-4b7c-bd55-b576c07bb09d",
"servicePlanName": "AAD_PREMIUM",
"provisioningStatus": "Success",
"appliesTo": "User"
```

for P2:
```
"servicePlanId": "eec0eb4f-6444-4f95-aba0-50c24d67f998",
"servicePlanName": "AAD_PREMIUM_P2",
"provisioningStatus": "Success",
"appliesTo": "User"
```

**Comment by jasoth** [comment]
Hmmm alright. We will take another look.
@cblomart can you look into this?
