### ISSUE TITLE
Not collecting the correct amount of users

### ISSUE THREAD

**Issue by donmagenium** [AzureAD/AzureADAssessment#58]
Running this for a client and it is only reporting approximately 1000 of 8000 users.  We have run multiple times, multiple source user accounts, same issue.  We have uninstalled, reinstalled, and force updated the module over a period of several weeks with no improvement.

**Comment by jasoth** [comment]
This is expected behavior. The assessment only retrieves users that are used and referenced elsewhere in the assessment. For example, they are assigned a privileged role or app role or have consented to an app, etc..
