### ISSUE TITLE
Does not contain 'Op_Addition' - 

### ISSUE THREAD

**Issue by ConnorRenada** [AzureAD/AzureADAssessment#59]
AzureADAssessment works fine on my Live Tenant however fails on my Developer Environment.

Not sure what it's asking for?

"
Test-MsGraphBatchError : Value cannot be null.
Parameter name: source
At C:\Program Files\WindowsPowerShell\Modules\AzureADAssessment\2.2.54\internal\Get-MsGraphResults.ps1:309 char:31
+ ...             if (!(Test-MsGraphBatchError $results $currentRequest)) {
+                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : ArgumentNullException,Test-MsGraphBatchError

WARNING: The export package has not been generated
WARNING: If you are working with microsoft or a provider on the assessment please warn them
WARNING: Please check GitHub issues and fill a new one or reply on existing ones mentionning the errors seen
WARNING: https://github.com/AzureAD/AzureADAssessment/issues
Method invocation failed because [System.Management.Automation.PSObject] does not contain a method named 'op_Addition'.
At C:\Program Files\WindowsPowerShell\Modules\AzureADAssessment\2.2.54\Invoke-AADAssessmentDataCollection.ps1:149
char:13
+             $roleAssignmentSchedules + $roleAssignmentSchedulesAdditi ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (op_Addition:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MethodNotFound "

**Comment by cblomart** [comment]
@ConnorRenada, did you have a chance to test with the latest version?
