### ISSUE TITLE
Authentication method registration not found for & Unable to find

### ISSUE THREAD

**Issue by vlfk-haakri** [AzureAD/AzureADAssessment#60]
Last successfull step: Loading users registration details in lookup cache
Then I see a lot(I mean a lot) of the following warnings:  WARNING: authentication method registration not found for <AAD user SID>

Common for all of the users are that they are disabled/blocked sign-in. 

The following occurs from the job:

Exporting UserReport: Completed 30 261 in 00:01:50
Loading groups in lookup cache
Exporting NotificationsEmailsReport: Completed 80 in 00:00:00
Loading administrative units in lookup cache
Loading applications in lookup cache
Loading service principals in lookup cache
Exporting RoleAssignmentReport: Completed 621 in 00:00:00
Exporting AppCredentialsReport: Completed 204 in 00:00:00
Exporting ConsentGrantReport: Completed 22 106 in 00:00:56
WARNING: The export package has not been generated
WARNING: If you are working with microsoft or a provider on the assessment please warn them
WARNING: Please check GitHub issues and fill a new one or reply on existing ones mentionning the errors seen
WARNING: https://github.com/AzureAD/AzureADAssessment/issues
Unable to find type [System.IO.Compression.ZipFile].
At C:\Users\<myusername>\Onedrive - mycompany\Documents\WindowsPowerShell\Modules\AzureADAssessment\2.2.54\Invo
ke-AADAssessmentDataCollection.ps1:345 char:13
+             [System.IO.Compression.ZipFile]::CreateFromDirectory($Out ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.IO.Compression.ZipFile:TypeName) [], ParentContainsErrorRecord
   Exception
    + FullyQualifiedErrorId : TypeNotFound

**Comment by cblomart** [comment]
These are warning because it is best to have all user register an MFA method.

if they are blocked they may have never been asked to add one.

Is the class issue on ZipFile also an issue? Please add another issue if it is :)

**Comment by vlfk-haakri** [comment]
Hi, the error occurs before the Zip file is made. But the csv files for administrativeUnits, AppCredentialsReport, appRoleAssignments and so on are available - along with the json files.

**Comment by jasoth** [comment]
@vlfk-haakri The zip issue might be resolved in the latest version and we decided to hide these warning on data collection. If there are specific recommendations in this area, we can surface those in the reporting itself rather than during data collection. Please try the latest release and let us know if you hit any other errors.
