### ISSUE TITLE
The property 'Count' cannot be found on this object. Verify that the property exists.

### ISSUE THREAD

**Issue by jserban** [AzureAD/AzureADAssessment#64]
I get this error when it tries to process Service Principles.  I am running it on Windows 11.

PS C:\Users\jserban\OneDrive - Microsoft\Documents\GitHub\AzureADAssessment> Invoke-AADAssessmentDataCollection
Exporting applications: Completed 2 in 00:00:00
Exporting appRoleAssignments: Completed 32 in 00:00:00
Exporting oauth2PermissionGrants: Completed 12 in 00:00:00
Exporting servicePrincipals (JSON): Completed 15 in 00:00:00
Exporting servicePrincipals (CSV): Completed 15 in 00:00:00
Exporting groups: Completed 7 in 00:00:00
Loading users in lookup cache
Loading users registration details in lookup cache
Exporting UserReport: Completed 11 in 00:00:00
Loading groups in lookup cache
Exporting NotificationsEmailsReport: Completed 9 in 00:00:00
Loading administrative units in lookup cache
Loading applications in lookup cache                                                                                    
Loading service principals in lookup cache                                                                              
WARNING: The export package has not been generated
WARNING: If you are working with microsoft or a provider on the assessment please warn them                             
WARNING: Please check GitHub issues and fill a new one or reply on existing ones mentionning the errors seen            
WARNING: https://github.com/AzureAD/AzureADAssessment/issues                                                            
Format-Csv: C:\Program Files\WindowsPowerShell\Modules\AzureADAssessment\2.2.64\Export-AADAssessmentReportData.ps1:226:11
Line |
 226 |          | Format-Csv `
     |            ~~~~~~~~~~
     | The property 'Count' cannot be found on this object. Verify that the property exists.

**Comment by albandrod** [comment]
same problem here

**Comment by albandrod** [comment]
Removing the line 251 makes the trick :)

**Comment by jasoth** [comment]
@albandrod removing line 251 does fix the error in PowerShell but unfortunately causes issues for the PowerBI template when PowerShell Core is used.
@jserban @albandrod I believe this bug is fixed now in the Format-Csv function and I pushed a preview release (2.3.1-preview) to PowerShell Gallery. Could both of you validate the new preview works?
```PowerShell
Update-Module AzureADAssessment -AllowPrerelease
```

**Comment by patrykszu** [comment]
I have the same problem and allowprerelease does not work for me :(

Update-Module : A parameter cannot be found that matches parameter name 'AllowPrerelease'.
At line:1 char:33
+ Update-Module AzureADAssessment -AllowPrerelease
+                                 ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Update-Module], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Update-Module

**Comment by cblomart** [comment]
Hi @patrykszu,

Can you try with PowerShell 7.2 ?
https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows?WT.mc_id=THOMASMAURER-blog-thmaure&view=powershell-7

Otherwise try to update PowerShellGet
https://learn.microsoft.com/en-us/powershell/scripting/gallery/installing-psget?view=powershell-7.2

**Comment by cblomart** [comment]
@jserban, @albandrod, @patrykszu, since the module was updated since, this issue should be closed.
The update module issue should be related to PowerShell installation to make update-module work correctly.

I will close this issue now. Don't hesitate to reply to reopen.
