### ISSUE TITLE
CA recommendation Office 365 Coverage check

### ISSUE THREAD

**Issue by hitem** [AzureAD/AzureADAssessment#68]
Hello Guys,
I have been running a few assessment as of late and have run in to a bug that keeps coming back. For multiple tenants, in the Conditional Access assessment report (powerbi) i get the following recommendation:
![image](https://user-images.githubusercontent.com/8977898/188096174-45cceced-d185-4981-83c3-ea1d52f62c8b.png)
However, the CA in question always has this:
![image](https://user-images.githubusercontent.com/8977898/188096407-e753208f-e0b2-4599-99d0-ee635a086bd8.png)
![image](https://user-images.githubusercontent.com/8977898/188097243-82fc4355-0068-4d44-b41e-db4d331c2eed.png)

I think this might be a bug, or am i missing something?

Greatly appreciated. keep up the good work!

**Comment by cblomart** [comment]
@tylchan can you have a look?
