### ISSUE TITLE
Add-AzureAssessmentTask doesn't support MFA parameter

### ISSUE THREAD

**Issue by lucafabbri365** [AzureAD/AzureADAssessment#72]
Hello,
maybe this isn't the right place however I discovered the **Add-AzureAssessmentTask** doesn't support the -MFA parameter (despite I can read it referenced in documentation).

```
Get-Command Add-AzureAssessmentTask

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Cmdlet          Add-AzureAssessmentTask                            8.0.1.1086 Microsoft.PowerShell.Oms.Assessments
```
I have installed the latest version of **Microsoft Monitoring Agent (MMA) v10.20.18067.0** available in Log Analytics workspaces.

This is my fault or it doesn't support the -MFA parameter anymore ?

**Comment by cblomart** [comment]
This command would correspond to the ondemand assessment and is not related to this repository,
Please contact the microsoft team with whom you installed the ondemand assessment

I will close this issue with this. If there is further questions on the AzureADAssessment, don't hesitate to answer here or open a new issue.
