### ISSUE TITLE
Explanation of a tab in the PowerBi report

### ISSUE THREAD

**Issue by Dsrygaard** [AzureAD/AzureADAssessment#73]
Hi guys

Can you please describe the App Keys tab in AzureADAssessment PowerBi document? 

Me and my team could not find a description regarding this. To me more precisely, its the 'Key Name' when the key type is password. 

If we got data in this column, does it show the username, password or what does it provide us of information? Because we got different kind of data in this column sometimes that confuse us. 

Thanks in advice

BR

**Comment by cblomart** [comment]
Hi @Dsrygaard,

The "Key Name" shown in the PowerBI report in the App Keys tab correspons to the "Description" of the application credential as found in Azure AD.
In graph API this would be the "displayName" of the credential:
https://learn.microsoft.com/en-us/graph/api/resources/passwordcredential?view=graph-rest-1.0
https://learn.microsoft.com/en-us/graph/api/resources/keycredential?view=graph-rest-1.0

Does that clarify this field?

Cédric

**Comment by cblomart** [comment]
@Dsrygaard, i hope the explanation given did resolve your issue.
I'll close the issue, don't hesitate to comment to reopen it.
