### ISSUE TITLE
AppKeys and expiration

### ISSUE THREAD

**Issue by atiedemann** [AzureAD/AzureADAssessment#77]
Hello all together,

I analyse the last assessment and I wonder why one app in my tenant is marked as expired. The App registration in this case has no certificate and no secret, so nothing can expire from my point of view.
What I see ist that the enddate is calculated, creation date plus two years and that is the expiration date.

Is this correct or is this an error?

**Comment by merill** [comment]
Can you please try to repro with the latest version? Tx.
