### ISSUE TITLE
Conditional Access polices with Preview features not collect as part of the assessment

### ISSUE THREAD

**Issue by kirk1256** [AzureAD/AzureADAssessment#79]
I noticed on my latest assessment that the Conditional Access policy PowerBI only had 9 polices as opposed to the actual 13 in azure, turns out that there are preview features in the policies (did not go in to details on what they were) and to collect those the AzureADPreview module is needed 

<img width="1199" alt="Screenshot 2023-02-02 at 14 39 17" src="https://user-images.githubusercontent.com/86346142/216340174-d5171500-5a95-4f41-9c59-d7e22e404a54.png">

**Comment by merill** [comment]
Can you please try with the latest version of the module? tx
