### ISSUE TITLE
Get-MsGraphResults Issue - $expand of back links is not supported for mega tenants - B2C tenant

### ISSUE THREAD

**Issue by mlinton** [AzureAD/AzureADAssessment#80]
Trying to collect data associated with a B2C tenant using this script, but getting an error.

Did read in a different post that support for backlinks wouldn't be supported for b2c.  Not sure if there is a workaround for this to get data from a b2c client.

**Comment by merill** [comment]
Hey @mlinton unfortunately we don't support assessing B2C tenants in the assessment at this time.
