### ISSUE TITLE
ForEach-Object: Cannot convert argument "item", with value: "MicrosoftAdminPortals"

### ISSUE THREAD

**Issue by isimaan** [AzureAD/AzureADAssessment#83]
Hi everyone,

I have an environment where the report creation fails with following  error:

ForEach-Object: Cannot convert argument "item", with value: "MicrosoftAdminPortals", for "Add" to type "System.Guid": "Cannot convert value "MicrosoftAdminPortals" to type "System.Guid". Error: "Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).""

How can I solve this please, any idea is welcome.

cheers

**Comment by isimaan** [comment]
@jasoth @merill do you guys maybe have an idea?

**Comment by grprasath164** [comment]
I am facing the same issue. Is there a solution to this?

**Comment by merill** [comment]
Please update to the latest version for the fix.
