### ISSUE TITLE
Error when accessing Conditional Access Policies

### ISSUE THREAD

**Issue by cosmosblack** [AzureAD/AzureADAssessment#86]
WARNING: The export package has not been generated
WARNING: If you are working with microsoft or a provider on the assessment please warn them
WARNING: Please check GitHub issues and fill a new one or reply on existing ones mentionning the errors seen
WARNING: https://github.com/AzureAD/AzureADAssessment/issues
ForEach-Object: Cannot convert argument "item", with value: "MicrosoftAdminPortals", for "Add" to type "System.Guid": "Cannot convert
value "MicrosoftAdminPortals" to type "System.Guid". Error: "Guid should contain 32 digits with 4 dashes
(xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).""

**Comment by merill** [comment]
Please update to the latest version and try
