### ISSUE TITLE
Cannot convert argument "item", with value: "Office365", for "Add" to type "System.Guid"

### ISSUE THREAD

**Issue by atiedemann** [AzureAD/AzureADAssessment#9]
Hello all together,

I try out this module in my test environment and in a second tenant and I get this error.

`ForEach-Object : Cannot convert argument "item", with value: "Office365", for "Add" to type "System.Guid": "Cannot convert value "Office365" to type "System.Guid". Error: "Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).""
At C:\Program Files\WindowsPowerShell\Modules\AzureADAssessment\2.0.776660\internal\Add-AadReferencesToCache.ps1:50 char:76
+ ... lications | ForEach-Object { [void]$ReferencedIdCache.appId.Add($_) } ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ForEach-Object], MethodException
    + FullyQualifiedErrorId : MethodArgumentConversionInvalidCastArgument,Microsoft.PowerShell.Commands.ForEachObjectCommand`

after this error, the Cmdlet stops.

The line where the error occurs, has this content:
Line:50 `$InputObject.conditions.applications.excludeApplications | ForEach-Object { [void]$ReferencedIdCache.appId.Add($_) }`

Does someone know the error?

Thanks
Arne

**Comment by cblomart** [comment]
Hi Arne,

'Office365' was not filtered out from excluded apps the same way it's done for included ones. I updated the code.
Could you verify if this solves the issue?

Cédric

**Comment by atiedemann** [comment]
Good morning Cèdric,

many thanks for your update. :-)
This error is now gone and works fine.

I get an other error now but for this I start a new issue.

Thanks a lot
Arne
